process:
  s101: localhost
  s102: localhost
  s103: localhost
  s104: localhost
  s105: localhost
  s106: localhost
  s201: localhost
  s202: localhost
  s203: localhost
  s204: localhost
  s205: localhost
  s206: localhost
  s301: localhost
  s302: localhost
  s303: localhost
  s304: localhost
  s305: localhost
  s306: localhost
  c101: localhost
  c102: localhost
  c103: localhost
  c104: localhost
  c105: localhost
  c106: localhost
  c107: localhost
  c108: localhost
  c109: localhost
  c110: localhost
  c111: localhost
  c112: localhost
  c113: localhost
  c114: localhost
  c115: localhost
  c116: localhost
  c117: localhost
  c118: localhost
  c201: localhost
  c202: localhost
  c203: localhost
  c204: localhost
  c205: localhost
  c206: localhost
  c207: localhost
  c208: localhost
  c209: localhost
  c210: localhost
  c211: localhost
  c212: localhost
  c213: localhost
  c214: localhost
  c215: localhost
  c216: localhost
  c217: localhost
  c218: localhost
  c301: localhost
  c302: localhost
  c303: localhost
  c304: localhost
  c305: localhost
  c306: localhost
  c307: localhost
  c308: localhost
  c309: localhost
  c310: localhost
  c311: localhost
  c312: localhost
  c313: localhost
  c314: localhost
  c315: localhost
  c316: localhost
  c317: localhost
  c318: localhost

host:
  localhost: 127.0.0.1
