host:
    s101: beaker-20
    s102: beaker-20
    s103: beaker-20
    s104: beaker-20
    s105: beaker-20
    s106: beaker-20
    s201: beaker-21
    s202: beaker-21
    s203: beaker-21
    s204: beaker-21
    s205: beaker-21
    s206: beaker-21
    s301: beaker-22
    s302: beaker-22
    s303: beaker-22
    s304: beaker-22
    s305: beaker-22
    s306: beaker-22
    c101: beaker-23
    c102: beaker-23
    c103: beaker-23
    c104: beaker-23
    c105: beaker-23
    c106: beaker-23
    c201: beaker-24
    c202: beaker-24
    c203: beaker-24
    c204: beaker-24
    c205: beaker-24
    c206: beaker-24
    c301: beaker-25
    c302: beaker-25
    c303: beaker-25
    c304: beaker-25
    c305: beaker-25
    c306: beaker-25
