# Mode: just Raft replication

mode:
  cc: none # concurrency control
  ab: fpga_raft # atomic broadcast
  read_only: occ
  batch: false
  retry: 20
  ongoing: 1 # per client

# Sites: 1 server, 5 replicas

site:
  server:
    - ["s101:8101", "s102:8102", "s103:8103", "s104:8104", "s105:8105"]

process:
  s101: localhost
  s102: localhost
  s103: localhost
  s104: localhost
  s105: localhost

host:
  localhost: 127.0.0.1
